### ISSUE TITLE
Stream Deck macOS 6.0 update broke plugin

### ISSUE THREAD

**Issue by markmonroy** [johnholbrook/streamdeck-pihole#12]
Hi,

I just updated to Elgato's Stream Deck 6.0 software on macOS Ventura. This plugin seems to have lost connection with my Pi-hole. 

- A yellow triangle with an exclamation point appears intermittently on the physical button
- Pressing the button no longer toggles blocking
- There are no longer any stats displayed
- macOS Version 13.0.1
- Pi-hole version 5.14.1
- Stream Deck version 6.0.0
- Settings left at default. My server is at pi.hole and my server is not password protected so no API key is available
- Problem remained after uninstalling/reinstalling the plugin.

![tempImageDSbwfl](https://user-images.githubusercontent.com/32033503/202185570-75da1b0f-fe20-49a6-9a69-64414e9e8a6c.gif)
![Screenshot 2022-11-16 at 7 53 10 AM](https://user-images.githubusercontent.com/32033503/202185764-88e3f1bb-df55-4c63-8d65-8043970ad81a.jpg)

Thanks.

**Comment by funkydrgonzo** [comment]
same here on windows

**Comment by dz-igner** [comment]
same here (Windows 11, Pi-hole v5.14.1 / FTL v5.19.2 / Web Interface v5.17, Stream Deck SW-Version 6.0.0.17703) - API connection

**Comment by markmonroy** [comment]
I see now that this is a known issue with Stream Deck 6.0 and is actually affecting numerous plugins. [Via Reddit:](https://www.reddit.com/r/StreamDeckSDK/comments/yxm1zb/cors_issue_since_upgrading_to_v6/)

> Stream Deck 6 has been upgraded to use Qt6 which uses an updated version of Chromium under the hood. This is causing CORs issues with some javascript Stream Deck plugins. We are actively working to resolve this issue!

Confirmed that this is what is affecting this plugin by [enabling the Stream Deck debugger](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging):

`code.html:1 Access to XMLHttpRequest at 'http://pi.hole/admin/api.php' from origin 'file://' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Houdini7** [comment]
There is a Beta StreamDeck app available. This has resolved the issue for me: https://www.reddit.com/r/StreamDeckSDK/comments/yxm1zb/comment/ix8lr1r/?utm_source=share&utm_medium=web2x&context=3

**Comment by ballinascreen-hacs** [comment]
> There is a Beta StreamDeck app available. This has resolved the issue for me: https://www.reddit.com/r/StreamDeckSDK/comments/yxm1zb/comment/ix8lr1r/?utm_source=share&utm_medium=web2x&context=3

Thanks for the heads-up - this fixed the problem for me too. 👍

**Comment by johnholbrook** [comment]
Thanks everyone for helping to track this down!

Looks like elgato has released Stream Deck 6.0.1 which fixes this problem, so I'm going to go ahead and close the issue.
