### ISSUE TITLE
StreamDeck not working

### ISSUE THREAD

**Issue by orddie** [johnholbrook/streamdeck-pihole#13]
Hello!
using stream deck XL with firmware 1.01.000
using StreamDeck software version 6.0.0.17703
Using Pi-hole 5.14.1

Piehole is NOT my default DNS server, however, pi.hole dns does resolve to the pihole server. 

I'm unable to get the API key to work.   Any logs I can look to see whats going on?

**Comment by orddie** [comment]
here are some logs. 

16:43:47.923 Hello World!
16:43:47.924 us.johnholbrook.pihole.temporarily-disable didReceiveSettings
16:43:47.924 {"b43a56eee844c0c06316a73f7ea77045":{"action":"us.johnholbrook.pihole.temporarily-disable","settings":{"disable_time":"30","ph_addr":"pi.hole","ph_key":"\"f5f19526170a7014c37c9b1715b527<My-API-KEY-Is-Repalced_here>f\"","stat":"ads_blocked_today","show_status":true},"poller":2}}
16:44:02.474 Hello World!
16:44:02.475 us.johnholbrook.pihole.temporarily-disable didReceiveSettings
16:44:02.475 {"b43a56eee844c0c06316a73f7ea77045":{"action":"us.johnholbrook.pihole.temporarily-disable","settings":{"disable_time":"30","ph_addr":"pi.hole","ph_key":"'f5f19526170a7014c37c9b1715b527<My-API-KEY-Is-Repalced_here>f'","stat":"ads_blocked_today","show_status":true},"poller":3}}

**Comment by Firecul** [comment]
Update to the latest stream deck and it should be fixed.
https://github.com/johnholbrook/streamdeck-pihole/issues/12

**Comment by orddie** [comment]
Thank you.  thought I had the most recent.  confirmed working.
