### ISSUE TITLE
Pi-Hole API changes breaks plugin api calls

### ISSUE THREAD

**Issue by marcandrelevesque** [johnholbrook/streamdeck-pihole#14]
Pi-hole Pi-hole [v5.14.2](https://github.com/pi-hole/pi-hole/releases/v5.14.2) FTL [v5.20](https://github.com/pi-hole/FTL/releases/v5.20) Web Interface [v5.18](https://github.com/pi-hole/AdminLTE/releases/v5.18) made changes to their API.

ref: https://github.com/pi-hole/AdminLTE/issues/2326
https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content

You need to update the plugin to make it works again with the latest version.

**Comment by billg118** [comment]
I just got a stream deck yesterday and couldn't figure out why it wouldn't work.

I looked in the code and it looks like its using the correct auth method so IDK If thats the issue or not.

Either way it sucks I cant get this to work.

**Comment by marcandrelevesque** [comment]
endpoint authentication is not global anymore,  John needs to modify this and hopefully can figure it out because this is beyond my level of programming/config skills.

**Comment by billg118** [comment]
I tinkered a bit and fixed it. I put in a pull request. If you want to fix it now just copy the change locally to your plugin.

https://github.com/johnholbrook/streamdeck-pihole/pull/15

**Comment by johnholbrook** [comment]
Hey, thanks everyone for letting me know about this.

I've accepted @billg118's PR and released v1.1.1 of the plugin which should fix this issue. The new version is available now on the [releases page](https://github.com/johnholbrook/streamdeck-pihole/releases) and I've submitted it to the stream deck store.

**Comment by johnholbrook** [comment]
On second thought, going to leave this issue open until 1.1.1 is available in the store.

**Comment by blacktwin** [comment]
Just installed ` v1.1.1` via release page. Fixed my connection issue! Thanks!

**Comment by johnholbrook** [comment]
1.1.1 is now available in the store.
