### ISSUE TITLE
Change text placement

### ISSUE THREAD

**Issue by Lezeko** [johnholbrook/streamdeck-pihole#16]
Hey is it possible to modify code somewhere to make texts displayed on stream deck center of button? Or any other ways to do that?

**Comment by johnholbrook** [comment]
Hi, you can change the text alignment (top, bottom, or center) for any action on the Stream Deck using the buttons circled in red:

<img width="656" alt="Screenshot 2022-12-30 at 9 42 52 AM" src="https://user-images.githubusercontent.com/3682581/210082604-576b9644-8098-437c-a2ff-eb64c9514a33.png">


If I'm misunderstanding what you're asking, please feel free to reopen the issue.
