### ISSUE TITLE
discrete dis/enable actions?

### ISSUE THREAD

**Issue by wkearney99** [johnholbrook/streamdeck-pihole#18]
I have more than one pi-hole instance running.  I'd like to use a multi-action button on the stream deck to toggle them on/off.  

I don't need to 'see' the state back on the multi-action, but wouldn't mind it if it was possible.  

This would work around trying to support multiple pi-hole instances in one button directly, and the complications that might come from errors with one blocking the other from getting set (or their getting out of sync).

**Comment by johnholbrook** [comment]
This feature was added in version 1.2.0, which is now available from the [releases page](https://github.com/johnholbrook/streamdeck-pihole/releases/tag/v1.2.0) or from the [stream deck store](https://apps.elgato.com/plugins/us.johnholbrook.pihole).
