### ISSUE TITLE
Port Number

### ISSUE THREAD

**Issue by KuKuPuffs** [johnholbrook/streamdeck-pihole#2]
My Pi-Hole sits on a different port number. Is it possible for your plugin to support that?

example http://pi.hole:8080

**Comment by johnholbrook** [comment]
That configuration should be supported already – just put `pi.hole:8080` (or whatever address/port combination you need) in the "address" field. I just confirmed that that works on my end.

**Comment by KuKuPuffs** [comment]
Thanks for the quick reply and confirming the port number is supported. I still have some trouble getting this to work. I will debug further on my end as it may have to do with my Pi hole docker install.

**Comment by johnholbrook** [comment]
If you can access the Pi-hole admin interface at `http://pi-hole:8080/admin` in a web browser on the same machine, then the Streamdeck plugin should have no trouble talking to pi-hole.

One thing I can think of is, the address should just be the domain name or IP address, and port number if applicable – if you also include `http://` at the beginning, then the plugin will try to make requests to (e.g.), `http://http://pi.hole`, which will not work. I should probably check for that in the next version.

**Comment by KuKuPuffs** [comment]
that was the issue. I was putting in HTTP into the form. putting just p.hole:8080 works along with the direct IP address as well

Thank you for your help!
