### ISSUE TITLE
Yellow caution sign flashing despite connectivity to Pi

### ISSUE THREAD

**Issue by robotdrake** [johnholbrook/streamdeck-pihole#3]
Hello,
Let me first say this is a nice addition for the stream deck.

My issue:
Using the toggle button I have loaded the API key, and the toggle works as expected. I am able to use the button and see the pi hole disabled in the web console. On the flip side, I am able to enable / disable from the web console, and see the change reflected in the stream deck. I also see the statistics. 

Despite all that, I have a yellow caution sign flashing on my stream deck. If there is an update to the display info or the enabled / disabled status of the pi hole the caution sign will stop flashing for a brief moment, update, then continue flashing.

Any idea what would be causing this? My network setup is fairly unremarkable; both the pi and the computer the deck is attached to are wired on a home LAN.

**Comment by robotdrake** [comment]
Disregard this. After rebooting the stream deck, the PC, and the Pi one of those seems to have resolved it.

**Comment by johnholbrook** [comment]
Thanks, glad to hear you find the plugin useful!

**Comment by fcc48** [comment]
I have the same issue, but a reboot did not help.
http://${settings.ph_addr}/admin/api.php?${cmd}&auth=${settings.ph_key}
with filled parameters in my browser works.

**Comment by johnholbrook** [comment]
Hmm... What is the exact contents of your "address" field?

**Comment by fcc48** [comment]
Just the IP
https://i.imgur.com/l3NVpI5.png
